#ifndef VOID_GAME_ANIM_SEQUENCES
#define VOID_GAME_ANIM_SEQUENCES

enum EPlayerAnim
{
	PLAYER_NONE = 0,
	PLAYER_STAND = 1,
	PLAYER_RUN,
	PLAYER_ATTACK,
	PLAYER_PAIN1,
	PLAYER_PAIN2,
	PLAYER_PAIN3,
	PLAYER_JUMP,
	PLAYER_FLIP,
	PLAYER_SALUTE,
	PLAYER_TAUNT,
	PLAYER_WAVE,
	PLAYER_POINT,
	PLAYER_CROUCH_STAND,
	PLAYER_CROUCH_WALK,
	PLAYER_CROUCH_ATTACK,
	PLAYER_CROUCH_PAIN,
	PLAYER_CROUCH_DEATH,
	PLAYER_DEATH1,
	PLAYER_DEATH2,
	PLAYER_DEATH3
};

namespace ClAnim {

enum
{
	STAND_BEGIN = 0,
	STAND_END = 39,
	
	RUN_BEGIN = 40,
	RUN_END = 45,

	ATTACK_BEGIN = 46,
	ATTACK_END = 53,

	PAIN1_BEGIN = 54,
	PAIN1_END = 57,

	PAIN2_BEGIN = 58,
	PAIN2_END = 61,

	PAIN3_BEGIN = 62,
	PAIN3_END = 65,

	JUMP_BEGIN = 66,
	JUMP_END = 71,

	FLIP_BEGIN = 72,
	FLIP_END = 83,

	SALUTE_BEGIN = 84,
	SALUTE_END = 94,

	TAUNT_BEGIN = 95,
	TAUNT_END = 111,

	WAVE_BEGIN = 112,
	WAVE_END = 122,

	POINT_BEGIN = 123,
	POINT_END = 134,

	CROUCH_STAND_BEGIN = 135,
	CROUCH_STAND_END = 153,

	CROUCH_WALK_BEGIN = 154,
	CROUCH_WALK_END = 159,

	CROUCH_ATTACK_BEGIN = 160,
	CROUCH_ATTACK_END = 168,

	CROUCH_PAIN_BEGIN = 169,
	CROUCH_PAIN_END = 172,

	CROUCH_DEATH_BEGIN = 173,
	CROUCH_DEATH_END = 177,

	DEATH1_BEGIN = 178,
	DEATH1_END = 183,

	DEATH2_BEGIN = 184,
	DEATH2_END = 189,

	DEATH3_BEGIN = 190,
	DEATH3_END = 197,
};


void SetAnim(AnimState &animState, EPlayerAnim anim)
{
	switch(anim)
	{
	case PLAYER_STAND:
		animState.Set(STAND_BEGIN,STAND_END);
	case PLAYER_RUN:
		animState.Set(RUN_BEGIN,RUN_END);
	case PLAYER_ATTACK:
		animState.Set(ATTACK_BEGIN,ATTACK_END);
	case PLAYER_PAIN1:
		animState.Set(PAIN1_BEGIN,PAIN1_END);
	case PLAYER_PAIN2:
		animState.Set(PAIN2_BEGIN,PAIN2_END);
	case PLAYER_PAIN3:
		animState.Set(PAIN3_BEGIN,PAIN3_END);
	case PLAYER_JUMP:
		animState.Set(JUMP_BEGIN,JUMP_END);
	case PLAYER_FLIP:
		animState.Set(FLIP_BEGIN,FLIP_END);
	case PLAYER_SALUTE:
		animState.Set(SALUTE_BEGIN,SALUTE_END);
	case PLAYER_TAUNT:
		animState.Set(TAUNT_BEGIN,TAUNT_END);
	case PLAYER_WAVE:
		animState.Set(WAVE_BEGIN,WAVE_END);
	case PLAYER_POINT:
		animState.Set(POINT_BEGIN,POINT_END);
	case PLAYER_CROUCH_STAND:
		animState.Set(CROUCH_STAND_BEGIN,CROUCH_STAND_END);
	case PLAYER_CROUCH_WALK:
		animState.Set(CROUCH_WALK_BEGIN,CROUCH_WALK_END);
	case PLAYER_CROUCH_ATTACK:
		animState.Set(CROUCH_ATTACK_BEGIN,CROUCH_ATTACK_END);
	case PLAYER_CROUCH_PAIN:
		animState.Set(CROUCH_PAIN_BEGIN,CROUCH_PAIN_END);
	case PLAYER_CROUCH_DEATH:
		animState.Set(CROUCH_DEATH_BEGIN,CROUCH_DEATH_END);
	case PLAYER_DEATH1:
		animState.Set(DEATH1_BEGIN,DEATH1_END);
	case PLAYER_DEATH2:
		animState.Set(DEATH2_BEGIN,DEATH2_END);
	case PLAYER_DEATH3:
		animState.Set(DEATH3_BEGIN,DEATH3_END);
	}
}


}

#endif